package com.wd.gui;

import com.wd.dominio.CentroDistribucion;
import com.wd.dominio.Empleado;
import com.wd.dominio.Lugar;
import com.wd.dominio.NominaCentro;
import com.wd.gui.controlparticular.ControlGuiEmpleadoCentro;
import com.wd.gui.controlparticular.ControlGuiLugar;
import com.wd.servicios.ControlEmpleado;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabylis
 */
public class VentanaPersonalCentro extends javax.swing.JFrame {

    private Vector<CentroDistribucion> vecCentros;

    private Vector<Lugar> vecCiudades;

    private ControlGuiLugar controlLugar;

    private Vector<Empleado> vecEmpleados;

    private Vector<NominaCentro> vecNomina;

    private DefaultTableModel dm;

    private ControlGuiEmpleadoCentro controlGuiEmpleadoCentro;
    

    /** Creates new form VentanaPersonalCentro */
    public VentanaPersonalCentro(Vector<CentroDistribucion> result) {
        initComponents();
        java.net.URL url = getClass().getResource("Iconos/icon_016.png");
        java.awt.Image imagen = getToolkit().getImage(url);
        setIconImage (imagen);

        vecNomina = new Vector();
        vecEmpleados = new Vector();

        vecCentros = new Vector();
        vecCentros = result;

        controlLugar = new ControlGuiLugar();
        vecCiudades = controlLugar.traerTodosLosLugares(2);

        dm = new DefaultTableModel();
        dm.addColumn("CI");
        dm.addColumn("Nombre");
        dm.addColumn("Apellido");
        dm.addColumn("Sexo");
        dm.addColumn("Fecha Nacimiento");
        dm.addColumn("Telefono");
        dm.addColumn("Cargo");
        dm.addColumn("Fecha Inicio");
        dm.addColumn("Fecha Fin");

        for (CentroDistribucion centroDistribucion : result) {
            this.comboCentro.addItem(centroDistribucion.getNombre());
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboCentro = new javax.swing.JComboBox();
        labelCentro = new javax.swing.JLabel();
        labelNombId = new javax.swing.JLabel();
        labelTelefonoNomb = new javax.swing.JLabel();
        labelDireccionNomb = new javax.swing.JLabel();
        labelUbicacionNomb = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelDir = new javax.swing.JLabel();
        labelUbicacion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        buttonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personal Centro de Distribución");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal por Centro de Distribución", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 204))); // NOI18N

        comboCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCentroActionPerformed(evt);
            }
        });

        labelCentro.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelCentro.setText("Centros De Distribución");

        labelNombId.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelNombId.setText("ID:");

        labelTelefonoNomb.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelTelefonoNomb.setText("Teléfono: ");

        labelDireccionNomb.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelDireccionNomb.setText("Dirección: ");

        labelUbicacionNomb.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelUbicacionNomb.setText("Ubicación: ");

        labelId.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelId.setForeground(new java.awt.Color(0, 102, 204));
        labelId.setText("ID");

        labelTelefono.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelTelefono.setForeground(new java.awt.Color(0, 102, 204));
        labelTelefono.setText("Telefono");

        labelDir.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelDir.setForeground(new java.awt.Color(0, 102, 204));
        labelDir.setText("Direccion");

        labelUbicacion.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelUbicacion.setForeground(new java.awt.Color(0, 102, 204));
        labelUbicacion.setText("ciudad+estado");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true), "Empleados Asociados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        buttonCerrar.setFont(new java.awt.Font("Tahoma", 1, 11));
        buttonCerrar.setText("Cerrar");
        buttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCentro)
                            .addComponent(labelNombId)
                            .addComponent(labelTelefonoNomb)
                            .addComponent(labelDireccionNomb)
                            .addComponent(labelUbicacionNomb))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUbicacion)
                            .addComponent(labelDir)
                            .addComponent(labelTelefono)
                            .addComponent(labelId)
                            .addComponent(comboCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(buttonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCentro)
                    .addComponent(comboCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombId)
                    .addComponent(labelId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefonoNomb)
                    .addComponent(labelTelefono))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccionNomb)
                    .addComponent(labelDir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbicacionNomb)
                    .addComponent(labelUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCerrar)
                .addGap(239, 239, 239))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCentroActionPerformed
        int select = -1;
        int codigoCentro = -1;
        int cityId = -1;
        String telefono = "";
        String direccion = "";
        String ubicacion = "";
        
        select = this.comboCentro.getSelectedIndex();
        CentroDistribucion centrico = new CentroDistribucion();
        centrico = this.vecCentros.elementAt(select);

        cityId = centrico.getLugarId();
        codigoCentro = centrico.getCodigo();
        telefono = centrico.getTelefono();
        direccion = centrico.getDireccion();
        ubicacion = this.getUbicacion(cityId);

        this.labelId.setText(codigoCentro+"");
        this.labelTelefono.setText(telefono);
        this.labelDir.setText(direccion);
        this.labelUbicacion.setText(ubicacion);

        this.llenarTabla(codigoCentro);
    }//GEN-LAST:event_comboCentroActionPerformed

    private void buttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_buttonCerrarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Vector<CentroDistribucion> result) {
                new VentanaPersonalCentro(result).setVisible(true);
            }
            public void run() {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrar;
    private javax.swing.JComboBox comboCentro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCentro;
    private javax.swing.JLabel labelDir;
    private javax.swing.JLabel labelDireccionNomb;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNombId;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTelefonoNomb;
    private javax.swing.JLabel labelUbicacion;
    private javax.swing.JLabel labelUbicacionNomb;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables

    public void llenarTabla(int codigoCentro){

        this.controlGuiEmpleadoCentro = new ControlGuiEmpleadoCentro();
        this.vecEmpleados = controlGuiEmpleadoCentro.traerTodosLosEmpleadosCentro(codigoCentro);
        this.vecNomina = controlGuiEmpleadoCentro.traerNominaCentro(codigoCentro);

        Empleado emp = new Empleado();
        NominaCentro nom = new NominaCentro();

        for (int i = 0; i < vecEmpleados.size(); i++){

                emp = vecEmpleados.elementAt(i);
                nom = vecNomina.elementAt(i);

                Vector info = new Vector();
                info.addElement(emp.getCedula());
                info.addElement(emp.getNombre());
                info.addElement(emp.getApellido());
                info.addElement(emp.getSexo());
                info.addElement(emp.getFechaNacimiento());                
                info.addElement(emp.getTelefono());
                if (nom.getCargo()==0)info.add("Gerente");
                if (nom.getCargo()==1)info.add("Regular");
                if (nom.getCargo()==2)info.add("Conductor");
                info.addElement(nom.getFechaIni());
                info.addElement(nom.getFechaFin());                
                dm.addRow(info);
            }

			this.tablaEmpleados.setModel(dm);

    }

    public String getUbicacion(int cityId){
        String nombreCity= "";
        String estado = "";
        String ubicacion = "";

        for (Lugar ciudad : vecCiudades) {
            if (ciudad.getId() == cityId){
                nombreCity = ciudad.getNombrePropio();
                estado = ciudad.getNombrePertenece();
                ubicacion = nombreCity + ", " + estado;
            }
        }
        return ubicacion;
    }
}
