/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaNuevaTienda.java
 *
 * Created on Dec 2, 2008, 6:33:17 PM
 */

package com.wd.gui;

import com.wd.dominio.EmpresaVigilancia;
import com.wd.dominio.Horario;
import com.wd.dominio.Lugar;
import com.wd.gui.controlparticular.ControlGuiEmpresaVigilancia;
import com.wd.gui.controlparticular.ControlGuiHorario;
import com.wd.gui.controlparticular.ControlGuiLugar;
import com.wd.gui.controlparticular.ControlGuiTienda;
import java.util.Vector;

/**
 *
 * @author Johnny
 */
public class VentanaNuevaTienda extends javax.swing.JFrame {
    
    private ControlGui control_general;

    private ControlGuiTienda control_gui_tienda;

    private ControlGuiHorario control_gui_horario;

    private Vector<Horario> horarios;

    private Horario horario_seleccion;

    private ControlGuiLugar control_gui_lugar;

    private Vector<Lugar> estados;

    private Lugar estado_seleccion;

    private Vector<Lugar> todas_las_ciudades;

    private Vector<Lugar> ciudades;

    private Lugar ciudad_seleccion;

    private ControlGuiEmpresaVigilancia control_gui_empresa;

    private Vector<EmpresaVigilancia> empresas;

    private EmpresaVigilancia empresa_seleccion;

    /** Creates new form VentanaNuevaTienda */
    public VentanaNuevaTienda() {
        initComponents();
        java.net.URL url = getClass().getResource("Iconos/icon_016.png");
        java.awt.Image imagen = getToolkit().getImage(url);
        setIconImage (imagen);
        this.inicializarControles();
        this.inicializarVectores();
        this.llenarComboBoxes();
    }

    /** Metodo para inicaliazar Controles */
    public void inicializarControles(){
        this.control_general = new ControlGui();
        this.control_gui_tienda = new ControlGuiTienda();
        this.control_gui_horario = new ControlGuiHorario();
        this.control_gui_lugar = new ControlGuiLugar();
        this.control_gui_empresa = new ControlGuiEmpresaVigilancia();
    }

    /** Metodo par iniciaclizar vectores */
    public void inicializarVectores(){
        this.horarios = this.control_gui_horario.traerTodosLosHorarios();
        this.estados = this.control_gui_lugar.traerTodosLosLugares(1);
        this.todas_las_ciudades = this.control_gui_lugar.traerTodosLosLugares(2);
        this.empresas = this.control_gui_empresa.traerTodasLasEmpresas();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_tamano = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_horarios = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jTextField_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_estados = new javax.swing.JComboBox();
        jComboBox_ciudades = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_direccion = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_empresas = new javax.swing.JComboBox();
        jButton_registrar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Tienda");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Tienda"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de la Tienda"));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 263));

        jTextField_nombre.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel1.setText("Nombre [*]");

        jLabel2.setText("Tamaño [*]");

        jTextField_tamano.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel4.setText("m²");

        jLabel3.setText("Horario [*]");

        jComboBox_horarios.setPreferredSize(new java.awt.Dimension(200, 20));
        jComboBox_horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_horariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addComponent(jComboBox_horarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de la Tienda"));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 263));

        jTextField_telefono.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel5.setText("Teléfono [*]");

        jLabel6.setText("Correo Electrónico [*]");

        jTextField_correo.setPreferredSize(new java.awt.Dimension(200, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Locación de la Tienda"));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 263));

        jLabel7.setText("Estado [*]");

        jLabel8.setText("Ciudad [*]");

        jComboBox_estados.setPreferredSize(new java.awt.Dimension(200, 20));
        jComboBox_estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_estadosActionPerformed(evt);
            }
        });

        jComboBox_ciudades.setPreferredSize(new java.awt.Dimension(200, 20));
        jComboBox_ciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ciudadesActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 66));
        jScrollPane1.setViewportView(jTextPane_direccion);

        jLabel9.setText("Dirección [*]");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(68, 68, 68)
                        .addComponent(jComboBox_estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_ciudades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox_ciudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicios"));
        jPanel5.setPreferredSize(new java.awt.Dimension(350, 263));

        jLabel10.setText("Empresa de Vigilancia");

        jComboBox_empresas.setPreferredSize(new java.awt.Dimension(200, 20));
        jComboBox_empresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_empresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jComboBox_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_registrar.setText("Registrar");
        jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarActionPerformed(evt);
            }
        });

        jButton_cancelar.setText("Cancelar");

        jLabel11.setText("[*] Campos obligatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_cancelar)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_registrar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_registrar)
                    .addComponent(jButton_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_horariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_horariosActionPerformed
        int index = this.jComboBox_horarios.getSelectedIndex();
        if (index != -1){
            this.horario_seleccion = this.horarios.get(index);
            System.out.println("Horario: " + this.horario_seleccion.getId());
        } else {
            this.horario_seleccion = null;
            System.out.println("Horario: no hay seleccion");
        }
    }//GEN-LAST:event_jComboBox_horariosActionPerformed

    private void jComboBox_estadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_estadosActionPerformed
        int index = this.jComboBox_estados.getSelectedIndex();
        if (index != -1){
            this.estado_seleccion = this.estados.get(index);
            this.llenarCiudades(this.estado_seleccion.getId());
            System.out.println("Estado: " + this.estado_seleccion.getId() + " " + this.estado_seleccion.getNombrePropio());
        } else {
            this.estado_seleccion = null;
            System.out.println("Estado: no hay seleccion");
        }
    }//GEN-LAST:event_jComboBox_estadosActionPerformed

    private void jComboBox_ciudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ciudadesActionPerformed
        int index = this.jComboBox_ciudades.getSelectedIndex();
        if (index != -1){
            this.ciudad_seleccion = this.ciudades.get(index);
            System.out.println("Ciudad: " + this.ciudad_seleccion.getId()+ " " + this.ciudad_seleccion.getNombrePropio());
        } else {
            this.ciudad_seleccion = null;
            System.out.println("Ciudad: no hay seleccion");
        }
    }//GEN-LAST:event_jComboBox_ciudadesActionPerformed

    private void jComboBox_empresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_empresasActionPerformed
        int index = this.jComboBox_empresas.getSelectedIndex();
        if (index != -1){
            this.empresa_seleccion = this.empresas.get(index);
            System.out.println("Empresa: " + this.empresa_seleccion.getRif());
        } else {
            this.empresa_seleccion = null;
            System.out.println("Empresa: no hay seleccion");
        }
    }//GEN-LAST:event_jComboBox_empresasActionPerformed

    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
        if (this.validarFormulario()){
        this.control_gui_tienda.agregarTienda(this.jTextField_nombre.getText(),
                Integer.parseInt(this.jTextField_tamano.getText()),
                this.horario_seleccion.getId(),
                this.jTextField_telefono.getText(),
                this.jTextField_correo.getText(),
                this.ciudad_seleccion.getId(),
                this.jTextPane_direccion.getText(),
                this.empresa_seleccion.getRif());
        } else {
//            this.control_general.mostrarMensaje("Existen errores en los datos. Verifiquelos e intentelo nuevamente.", 1);
        }
    }//GEN-LAST:event_jButton_registrarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaNuevaTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_registrar;
    private javax.swing.JComboBox jComboBox_ciudades;
    private javax.swing.JComboBox jComboBox_empresas;
    private javax.swing.JComboBox jComboBox_estados;
    private javax.swing.JComboBox jComboBox_horarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_correo;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_tamano;
    private javax.swing.JTextField jTextField_telefono;
    private javax.swing.JTextPane jTextPane_direccion;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para llenar el jComboBox de horarios
     */
    private void llenarHorarios(){
        this.jComboBox_horarios.removeAllItems();
        for (Horario horario : this.horarios){
           this.jComboBox_horarios.addItem(horario.getDiaIni()
                   + " - " + horario.getDiaFin() + " : " +
                   horario.getHoraIni() + " - " + horario.getHoraFin());
        }
    }

    /**
     * Metodo para llenar el jComboBox de Estados
     */
    private void llenarEstados(){
        this.jComboBox_estados.removeAllItems();
        for (Lugar estado : this.estados){
           this.jComboBox_estados.addItem(estado.getNombrePropio());
        }
    }

    /**
     * Metodo para llenar el jComboBox de Ciudades.
     * Las Ciudades van a depender del Estado seleccionado previamente.
     * @param lugar_id el identificador del Estado.
     */
    private void llenarCiudades(int estado_id){
        this.seleccionarCiudades(estado_id);
        this.jComboBox_ciudades.removeAllItems();
        for (Lugar ciudad : this.ciudades){
            this.jComboBox_ciudades.addItem(ciudad.getNombrePropio());
        }
//        for (Lugar ciudad : this.todas_las_ciudades){
//            if (ciudad.getLugarID() == estado_id)
//                this.jComboBox_ciudades.addItem(ciudad.getNombrePropio());
//        }
    }

    /**
     * Metodo para llenar el jComboBox de Empresas de Vigilancia
     */
    private void llenarEmpresas(){
        this.jComboBox_empresas.removeAllItems();
        this.empresas.add(0, new EmpresaVigilancia());
        for (EmpresaVigilancia empresa : this.empresas){
            if (empresa.getRif() == null){
                this.jComboBox_empresas.addItem("NINGUNA");
            } else {
                this.jComboBox_empresas.addItem(empresa.getRif() + ": " +
                    empresa.getNombre());
            }
        }
    }

    /**
     * Metodo para invocar a los metodos de llenado de cada jComboBox
     */
    private void llenarComboBoxes(){
        this.llenarHorarios();
        this.llenarEstados();
        this.llenarEmpresas();
    }

    /**
     * Metodo para validar el llenado correcto del formulario
     * @return la validez del formulario
     */
    private boolean  validarFormulario(){
        if (this.jTextField_nombre.getText().isEmpty()){
            this.control_general.mostrarMensaje("Debe indicar una valor para Nombre", 1);
            return false;
        }
        if (this.jTextField_tamano.getText().isEmpty()){
            this.control_general.mostrarMensaje("Debe indicar una valor para Tamaño", 1);
            return false;
        }
        if (!this.esEntero(this.jTextField_tamano.getText())){
            this.control_general.mostrarMensaje("El valor de Tamaño debe ser un número  entero", 1);
            return false;
        }
        if (this.jComboBox_horarios.getSelectedIndex() == -1){
            this.control_general.mostrarMensaje("Debe seleccionar un Horario", 1);
            return false;
        }
        if (this.jTextField_telefono.getText().isEmpty()){
            this.control_general.mostrarMensaje("Debe indicar una valor para Teléfono", 1);
            return false;
        }
//        if (!this.esEntero(this.jTextField_telefono.getText())){
//            this.control_general.mostrarMensaje("El valor de Teléfono debe contener dígitos unicamente", 1);
//            return false;
//        }
        if (this.jTextField_correo.getText().isEmpty()){
            this.control_general.mostrarMensaje("Debe indicar una valor para Correo Electrónico", 1);
            return false;
        }
        if (this.jComboBox_ciudades.getSelectedIndex() == -1){
            this.control_general.mostrarMensaje("Debe seleccionar una Ciudad", 1);
            return false;
        }
        if (this.jTextPane_direccion.getText().isEmpty()){
            this.control_general.mostrarMensaje("Debe indicar una valor para Dirección", 1);
            return false;
        }
        return true;
    }

    /**
     * Metodo que verifica que un String contenga solo digitos.
     * @param string el string a verificar
     * @return
     */
    public boolean esEntero(String string){
        try {
            Integer.parseInt(string);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * metodo para deleccionar todas las Ciudades de un Estado
     * @param estado_id el id del Estado
     */
    public void seleccionarCiudades(int estado_id){
        this.ciudades = new Vector<Lugar>();
        for (Lugar ciudad : this.todas_las_ciudades) {
            if (ciudad.getLugarID() == estado_id){
                this.ciudades.add(ciudad);
            }
        }
    }

}