/*
 * VentanaInicio.java
 *
 * Created on November 18, 2008, 4:44 PM
 */

package com.wd.gui;

import com.wd.dominio.CentroDistribucion;
import com.wd.dominio.Departamento;
import com.wd.dominio.EmpresaVigilancia;
import com.wd.dominio.Horario;
import com.wd.dominio.Lugar;
import com.wd.dominio.Producto;
import com.wd.dominio.Tienda;
import com.wd.gui.controlparticular.ControlGuiCentroDistribucion;
import com.wd.gui.controlparticular.ControlGuiDepartamento;
import com.wd.gui.controlparticular.ControlGuiHorario;
import com.wd.gui.controlparticular.ControlGuiLugar;
import com.wd.gui.controlparticular.ControlGuiProducto;
import com.wd.gui.controlparticular.ControlGuiTienda;
import com.wd.guiSolicitud.VentanaProcesarPedidoSeleccion;
import java.util.Collection;
import java.util.Vector;


/**
 *
 * @author  Johnny
 */
public class VentanaInicio extends javax.swing.JFrame {

    private ControlGui controlGeneralGui;
    private ControlGuiHorario controlGuiHorario;
    private ControlGuiDepartamento controlGuiDepartamento;
    private ControlGuiCentroDistribucion controlGuiCentro;
    private ControlGuiLugar controlGuiLugar;
    private ControlGuiTienda controlGuiTienda;
    private ControlGuiProducto controlGuiProducto;

    /** Creates new form VentanaInicio */
    public VentanaInicio() {
        initComponents();
        java.net.URL url = getClass().getResource("Iconos/icon_016.png");
        java.awt.Image imagen = getToolkit().getImage(url);
        setIconImage (imagen);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArcecaDe = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuTiendas = new javax.swing.JMenu();
        menuMantenimientoTienda = new javax.swing.JMenu();
        menuRegistrarTienda = new javax.swing.JMenuItem();
        menuEditarTienda = new javax.swing.JMenuItem();
        menuConsultarTienda = new javax.swing.JMenuItem();
        menuEliminarTienda = new javax.swing.JMenuItem();
        menuNominaTienda = new javax.swing.JMenu();
        menuAgregarEmpleadoTienda = new javax.swing.JMenuItem();
        menuEditarEmpleadoTienda = new javax.swing.JMenuItem();
        menuEliminarEmpleadoTienda = new javax.swing.JMenuItem();
        menuSeparadorTienda = new javax.swing.JSeparator();
        menuTransferirEmpleadoTienda = new javax.swing.JMenuItem();
        menuInventarioTienda = new javax.swing.JMenu();
        menuConsultaInventarioTienda = new javax.swing.JMenuItem();
        menuConsultaCentrosTienda = new javax.swing.JMenuItem();
        menuSolicitudesTienda = new javax.swing.JMenu();
        menuTransferenciasTienda = new javax.swing.JMenuItem();
        menuSeparadorDosTienda = new javax.swing.JSeparator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuTiendasSeparador = new javax.swing.JSeparator();
        menuEstadisticasTienda = new javax.swing.JMenuItem();
        menuCentros = new javax.swing.JMenu();
        menuCentroMantenimiento = new javax.swing.JMenu();
        menuCentroRegistro = new javax.swing.JMenuItem();
        menuCentroEditar = new javax.swing.JMenuItem();
        menuCentroConsultar = new javax.swing.JMenuItem();
        menuCentroEliminar = new javax.swing.JMenuItem();
        menuCentroNomina = new javax.swing.JMenu();
        menuCentroNominaAgregarEmpleado = new javax.swing.JMenuItem();
        menuCentroNominaEditarEmpleado = new javax.swing.JMenuItem();
        menuCentroNominaEliminarEmpleado = new javax.swing.JMenuItem();
        menuCentroNominaSeparador = new javax.swing.JSeparator();
        menuCentroNominaTrasnferirEmpelado = new javax.swing.JMenuItem();
        menuCentroSolicitudes = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuCentroSolicitudesPedidosTiendas = new javax.swing.JMenuItem();
        menuCentroInventarios = new javax.swing.JMenu();
        menuCentroInventarioConsultar = new javax.swing.JMenuItem();
        menuCentroInventarioConsultarProvedores = new javax.swing.JMenuItem();
        menuCentroCamiones = new javax.swing.JMenu();
        menuCentroCamionRegistro = new javax.swing.JMenuItem();
        menuCentroCamionEditar = new javax.swing.JMenuItem();
        menuCentroCamionConsulta = new javax.swing.JMenuItem();
        menuCentroCamionEliminar = new javax.swing.JMenuItem();
        menuCentroCamionAgregarCamionSuelto = new javax.swing.JMenuItem();
        menuCentroAsignarProvedores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuCentroSeparador = new javax.swing.JSeparator();
        menuCentroEstadisticas = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        menuProductosMantenimiento = new javax.swing.JMenu();
        MenuProductosAgregar = new javax.swing.JMenuItem();
        menuProductosEditar = new javax.swing.JMenuItem();
        menuProductosConsultar = new javax.swing.JMenuItem();
        menuProductosEliminar = new javax.swing.JMenuItem();
        menuProductosDepartamentos = new javax.swing.JMenu();
        menuProductosDepartamentosAgregar = new javax.swing.JMenuItem();
        menuProductosDepartamentosEditar = new javax.swing.JMenuItem();
        menuProductosDepartamentosConsultar = new javax.swing.JMenuItem();
        menuProductosDepartamentosEliminar = new javax.swing.JMenuItem();
        menuProductosClases = new javax.swing.JMenu();
        menuProductosClaseAgregar = new javax.swing.JMenuItem();
        menuProductosClaseEditar = new javax.swing.JMenuItem();
        menuProductosClaseConsultar = new javax.swing.JMenuItem();
        menuProductosClaseEliminar = new javax.swing.JMenuItem();
        menuProductosSubClases = new javax.swing.JMenu();
        menuProductosSubAgregar = new javax.swing.JMenuItem();
        menuProductosSubConsultar = new javax.swing.JMenuItem();
        menuProductosSubEliminar = new javax.swing.JMenuItem();
        menuProductosSeparador = new javax.swing.JSeparator();
        menuProductosConsultarPrecios = new javax.swing.JMenuItem();
        menuProductosEstadisticas = new javax.swing.JMenuItem();
        menuServicios = new javax.swing.JMenu();
        menuServiciosVigilancia = new javax.swing.JMenu();
        menuServiciosVigilanciaAgregar = new javax.swing.JMenuItem();
        menuServiciosVigilanciaEditar = new javax.swing.JMenuItem();
        menuServiciosVigilanciaConsultar = new javax.swing.JMenuItem();
        menuServiciosVigilanciaEliminar = new javax.swing.JMenuItem();
        menuServiciosProvedores = new javax.swing.JMenu();
        menuServiciosProvedoresAgregar = new javax.swing.JMenuItem();
        menuServiciosProvedoresConsultar = new javax.swing.JMenuItem();
        menuServiciosProvedoresEliminar = new javax.swing.JMenuItem();
        menuServiciosProvedorSeparador = new javax.swing.JSeparator();
        menuServiciosProvedorAgregarProductos = new javax.swing.JMenuItem();
        menusSeriviciosProvedoreEditarProductos = new javax.swing.JMenuItem();
        menuServiciosProvedorEliminarProductos = new javax.swing.JMenuItem();
        menuServiciosSeparador = new javax.swing.JSeparator();
        menuServiciosEstadisticas = new javax.swing.JMenuItem();
        menuUbicaciones = new javax.swing.JMenu();
        menuUbicacionesHorarios = new javax.swing.JMenu();
        menuUbicacionesHorarioAgregar = new javax.swing.JMenuItem();
        menuUbicacionesHorariosEliminar = new javax.swing.JMenuItem();
        menuUbicacionesLugares = new javax.swing.JMenu();
        menuUbicacionesLugarNuevo = new javax.swing.JMenuItem();
        menuUbicacionesLugarConsulta = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenu();
        menuHistorialTiendas = new javax.swing.JMenuItem();
        menuHistorialCentros = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Well Dressing");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Imagenes/img.png"))); // NOI18N
        jLabel1.setToolTipText("Bienvenidos al Sistema WellDressing");

        menuArchivo.setText("Archivo");

        menuArcecaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuArcecaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/icon_016.png"))); // NOI18N
        menuArcecaDe.setText("Acerca de...");
        menuArcecaDe.setToolTipText("Informacion sobre el Grupo de Desarrollo");
        menuArchivo.add(menuArcecaDe);

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/quit.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSalir);

        menuBar.add(menuArchivo);

        menuTiendas.setText("Tiendas");

        menuMantenimientoTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/editdd.png"))); // NOI18N
        menuMantenimientoTienda.setText("Mantenimiento");

        menuRegistrarTienda.setText("Registro de tienda");
        menuRegistrarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarTiendaActionPerformed(evt);
            }
        });
        menuMantenimientoTienda.add(menuRegistrarTienda);

        menuEditarTienda.setText("Editar una tienda");
        menuEditarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarTiendaActionPerformed(evt);
            }
        });
        menuMantenimientoTienda.add(menuEditarTienda);

        menuConsultarTienda.setText("Consultar una tienda");
        menuConsultarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarTiendaActionPerformed(evt);
            }
        });
        menuMantenimientoTienda.add(menuConsultarTienda);

        menuEliminarTienda.setText("Eliminar una tienda");
        menuEliminarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarTiendaActionPerformed(evt);
            }
        });
        menuMantenimientoTienda.add(menuEliminarTienda);

        menuTiendas.add(menuMantenimientoTienda);

        menuNominaTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/edit_group.png"))); // NOI18N
        menuNominaTienda.setText("Nomina");

        menuAgregarEmpleadoTienda.setText("Agregar un empleado");
        menuAgregarEmpleadoTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarEmpleadoTiendaActionPerformed(evt);
            }
        });
        menuNominaTienda.add(menuAgregarEmpleadoTienda);

        menuEditarEmpleadoTienda.setText("Consultar o editar empleado");
        menuEditarEmpleadoTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarEmpleadoTiendaActionPerformed(evt);
            }
        });
        menuNominaTienda.add(menuEditarEmpleadoTienda);

        menuEliminarEmpleadoTienda.setText("Eliminar un empleado");
        menuEliminarEmpleadoTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarEmpleadoTiendaActionPerformed(evt);
            }
        });
        menuNominaTienda.add(menuEliminarEmpleadoTienda);
        menuNominaTienda.add(menuSeparadorTienda);

        menuTransferirEmpleadoTienda.setText("Transferir empleado");
        menuTransferirEmpleadoTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransferirEmpleadoTiendaActionPerformed(evt);
            }
        });
        menuNominaTienda.add(menuTransferirEmpleadoTienda);

        menuTiendas.add(menuNominaTienda);

        menuInventarioTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/note_edit.png"))); // NOI18N
        menuInventarioTienda.setText("Inventario");

        menuConsultaInventarioTienda.setText("Consulta de inventario");
        menuConsultaInventarioTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaInventarioTiendaActionPerformed(evt);
            }
        });
        menuInventarioTienda.add(menuConsultaInventarioTienda);

        menuConsultaCentrosTienda.setText("Consulta de centros");
        menuInventarioTienda.add(menuConsultaCentrosTienda);

        menuTiendas.add(menuInventarioTienda);

        menuSolicitudesTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/money.png"))); // NOI18N
        menuSolicitudesTienda.setText("Solicitudes");

        menuTransferenciasTienda.setText("Transferencias");
        menuSolicitudesTienda.add(menuTransferenciasTienda);
        menuSolicitudesTienda.add(menuSeparadorDosTienda);

        jMenu2.setText("Pedidos");

        jMenuItem2.setText("Realizar Pedido");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Consultar y Editar");
        jMenu2.add(jMenuItem6);

        menuSolicitudesTienda.add(jMenu2);

        menuTiendas.add(menuSolicitudesTienda);
        menuTiendas.add(menuTiendasSeparador);

        menuEstadisticasTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/chart_bar_edit.png"))); // NOI18N
        menuEstadisticasTienda.setText("Estadisticas");
        menuEstadisticasTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadisticasTiendaActionPerformed(evt);
            }
        });
        menuTiendas.add(menuEstadisticasTienda);

        menuBar.add(menuTiendas);

        menuCentros.setText("Centros");

        menuCentroMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/editdd.png"))); // NOI18N
        menuCentroMantenimiento.setText("Mantenimiento");

        menuCentroRegistro.setText("Agregar centro");
        menuCentroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroRegistroActionPerformed(evt);
            }
        });
        menuCentroMantenimiento.add(menuCentroRegistro);

        menuCentroEditar.setText("Editar un centro");
        menuCentroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroEditarActionPerformed(evt);
            }
        });
        menuCentroMantenimiento.add(menuCentroEditar);

        menuCentroConsultar.setText("Consultar un centro");
        menuCentroConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroConsultarActionPerformed(evt);
            }
        });
        menuCentroMantenimiento.add(menuCentroConsultar);

        menuCentroEliminar.setText("Eliminar un centro");
        menuCentroEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroEliminarActionPerformed(evt);
            }
        });
        menuCentroMantenimiento.add(menuCentroEliminar);

        menuCentros.add(menuCentroMantenimiento);

        menuCentroNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/edit_group.png"))); // NOI18N
        menuCentroNomina.setText("Nomina");

        menuCentroNominaAgregarEmpleado.setText("Agregar un empleado");
        menuCentroNominaAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroNominaAgregarEmpleadoActionPerformed(evt);
            }
        });
        menuCentroNomina.add(menuCentroNominaAgregarEmpleado);

        menuCentroNominaEditarEmpleado.setText("Consultar o editar un empleado");
        menuCentroNominaEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroNominaEditarEmpleadoActionPerformed(evt);
            }
        });
        menuCentroNomina.add(menuCentroNominaEditarEmpleado);

        menuCentroNominaEliminarEmpleado.setText("Eliminar un empleado");
        menuCentroNominaEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroNominaEliminarEmpleadoActionPerformed(evt);
            }
        });
        menuCentroNomina.add(menuCentroNominaEliminarEmpleado);
        menuCentroNomina.add(menuCentroNominaSeparador);

        menuCentroNominaTrasnferirEmpelado.setText("Transferir empleado");
        menuCentroNominaTrasnferirEmpelado.setEnabled(false);
        menuCentroNomina.add(menuCentroNominaTrasnferirEmpelado);

        menuCentros.add(menuCentroNomina);

        menuCentroSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/money.png"))); // NOI18N
        menuCentroSolicitudes.setText("Solicitudes");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/cart.png"))); // NOI18N
        jMenu1.setText("Ordenes de compra");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Realizar Orden Compra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Consultar o Editar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        menuCentroSolicitudes.add(jMenu1);

        menuCentroSolicitudesPedidosTiendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/cart_remove.png"))); // NOI18N
        menuCentroSolicitudesPedidosTiendas.setText("Pedidos realizados de tiendas");
        menuCentroSolicitudes.add(menuCentroSolicitudesPedidosTiendas);

        menuCentros.add(menuCentroSolicitudes);

        menuCentroInventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/note_edit.png"))); // NOI18N
        menuCentroInventarios.setText("Inventario");

        menuCentroInventarioConsultar.setText("Consulta de inventario");
        menuCentroInventarioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroInventarioConsultarActionPerformed(evt);
            }
        });
        menuCentroInventarios.add(menuCentroInventarioConsultar);

        menuCentroInventarioConsultarProvedores.setText("Consulta de proveedores");
        menuCentroInventarioConsultarProvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroInventarioConsultarProvedoresActionPerformed(evt);
            }
        });
        menuCentroInventarios.add(menuCentroInventarioConsultarProvedores);

        menuCentros.add(menuCentroInventarios);

        menuCentroCamiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/lorry_add.png"))); // NOI18N
        menuCentroCamiones.setText("Camiones");

        menuCentroCamionRegistro.setText("Registro de camion");
        menuCentroCamionRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroCamionRegistroActionPerformed(evt);
            }
        });
        menuCentroCamiones.add(menuCentroCamionRegistro);

        menuCentroCamionEditar.setText("Editar un camion");
        menuCentroCamionEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroCamionEditarActionPerformed(evt);
            }
        });
        menuCentroCamiones.add(menuCentroCamionEditar);

        menuCentroCamionConsulta.setText("Consultar un camion");
        menuCentroCamionConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroCamionConsultaActionPerformed(evt);
            }
        });
        menuCentroCamiones.add(menuCentroCamionConsulta);

        menuCentroCamionEliminar.setText("Eliminar un camion");
        menuCentroCamionEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroCamionEliminarActionPerformed(evt);
            }
        });
        menuCentroCamiones.add(menuCentroCamionEliminar);

        menuCentroCamionAgregarCamionSuelto.setText("Agregar un camion a un centro");
        menuCentroCamiones.add(menuCentroCamionAgregarCamionSuelto);

        menuCentros.add(menuCentroCamiones);

        menuCentroAsignarProvedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/transmit_go.png"))); // NOI18N
        menuCentroAsignarProvedores.setText("Asignar Provedores");
        menuCentroAsignarProvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroAsignarProvedoresActionPerformed(evt);
            }
        });
        menuCentros.add(menuCentroAsignarProvedores);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/lock_go.png"))); // NOI18N
        jMenuItem1.setText("Asignar o renovar Vigilancia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCentros.add(jMenuItem1);
        menuCentros.add(menuCentroSeparador);

        menuCentroEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/chart_bar_edit.png"))); // NOI18N
        menuCentroEstadisticas.setText("Estadisticas");
        menuCentros.add(menuCentroEstadisticas);

        menuBar.add(menuCentros);

        menuProductos.setText("Productos");

        menuProductosMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/editdd.png"))); // NOI18N
        menuProductosMantenimiento.setText("Mantenimiento");

        MenuProductosAgregar.setText("Agregar producto");
        MenuProductosAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductosAgregarActionPerformed(evt);
            }
        });
        menuProductosMantenimiento.add(MenuProductosAgregar);

        menuProductosEditar.setText("Editar producto");
        menuProductosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosEditarActionPerformed(evt);
            }
        });
        menuProductosMantenimiento.add(menuProductosEditar);

        menuProductosConsultar.setText("Consultar producto");
        menuProductosConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosConsultarActionPerformed(evt);
            }
        });
        menuProductosMantenimiento.add(menuProductosConsultar);

        menuProductosEliminar.setText("Eliminar producto");
        menuProductosEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosEliminarActionPerformed(evt);
            }
        });
        menuProductosMantenimiento.add(menuProductosEliminar);

        menuProductos.add(menuProductosMantenimiento);

        menuProductosDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/knewstuff.png"))); // NOI18N
        menuProductosDepartamentos.setText("Departamentos");

        menuProductosDepartamentosAgregar.setText("Agregar departamento");
        menuProductosDepartamentosAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosDepartamentosAgregarActionPerformed(evt);
            }
        });
        menuProductosDepartamentos.add(menuProductosDepartamentosAgregar);

        menuProductosDepartamentosEditar.setText("Editar departamento");
        menuProductosDepartamentosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosDepartamentosEditarActionPerformed(evt);
            }
        });
        menuProductosDepartamentos.add(menuProductosDepartamentosEditar);

        menuProductosDepartamentosConsultar.setText("Consultar departamento");
        menuProductosDepartamentosConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosDepartamentosConsultarActionPerformed(evt);
            }
        });
        menuProductosDepartamentos.add(menuProductosDepartamentosConsultar);

        menuProductosDepartamentosEliminar.setText("Eliminar departamento");
        menuProductosDepartamentosEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosDepartamentosEliminarActionPerformed(evt);
            }
        });
        menuProductosDepartamentos.add(menuProductosDepartamentosEliminar);

        menuProductos.add(menuProductosDepartamentos);

        menuProductosClases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/agt_web.png"))); // NOI18N
        menuProductosClases.setText("Clases");

        menuProductosClaseAgregar.setText("Agregar clase");
        menuProductosClaseAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosClaseAgregarActionPerformed(evt);
            }
        });
        menuProductosClases.add(menuProductosClaseAgregar);

        menuProductosClaseEditar.setText("Editar clase");
        menuProductosClaseEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosClaseEditarActionPerformed(evt);
            }
        });
        menuProductosClases.add(menuProductosClaseEditar);

        menuProductosClaseConsultar.setText("Consultar clase");
        menuProductosClaseConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosClaseConsultarActionPerformed(evt);
            }
        });
        menuProductosClases.add(menuProductosClaseConsultar);

        menuProductosClaseEliminar.setText("Eliminar clase");
        menuProductosClaseEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosClaseEliminarActionPerformed(evt);
            }
        });
        menuProductosClases.add(menuProductosClaseEliminar);

        menuProductos.add(menuProductosClases);

        menuProductosSubClases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/sport_8ball.png"))); // NOI18N
        menuProductosSubClases.setText("Sub Clases");

        menuProductosSubAgregar.setText("Agregar sub clase");
        menuProductosSubAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosSubAgregarActionPerformed(evt);
            }
        });
        menuProductosSubClases.add(menuProductosSubAgregar);

        menuProductosSubConsultar.setText("Consultar sub clase");
        menuProductosSubClases.add(menuProductosSubConsultar);

        menuProductosSubEliminar.setText("Eliminar sub clase");
        menuProductosSubEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosSubEliminarActionPerformed(evt);
            }
        });
        menuProductosSubClases.add(menuProductosSubEliminar);

        menuProductos.add(menuProductosSubClases);
        menuProductos.add(menuProductosSeparador);

        menuProductosConsultarPrecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/money.png"))); // NOI18N
        menuProductosConsultarPrecios.setText("Consultar Precios");
        menuProductosConsultarPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosConsultarPreciosActionPerformed(evt);
            }
        });
        menuProductos.add(menuProductosConsultarPrecios);

        menuProductosEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/chart_bar_edit.png"))); // NOI18N
        menuProductosEstadisticas.setText("Estadisticas");
        menuProductosEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosEstadisticasActionPerformed(evt);
            }
        });
        menuProductos.add(menuProductosEstadisticas);

        menuBar.add(menuProductos);

        menuServicios.setText("Servicios");

        menuServiciosVigilancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/lock_go.png"))); // NOI18N
        menuServiciosVigilancia.setText("Servicio de vigilancia");

        menuServiciosVigilanciaAgregar.setText("Agregar servicio de vigilancia");
        menuServiciosVigilanciaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosVigilanciaAgregarActionPerformed(evt);
            }
        });
        menuServiciosVigilancia.add(menuServiciosVigilanciaAgregar);

        menuServiciosVigilanciaEditar.setText("Editar servicio de vigilancia");
        menuServiciosVigilanciaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosVigilanciaEditarActionPerformed(evt);
            }
        });
        menuServiciosVigilancia.add(menuServiciosVigilanciaEditar);

        menuServiciosVigilanciaConsultar.setText("Consultar servicio de vigilancia");
        menuServiciosVigilanciaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosVigilanciaConsultarActionPerformed(evt);
            }
        });
        menuServiciosVigilancia.add(menuServiciosVigilanciaConsultar);

        menuServiciosVigilanciaEliminar.setText("Eliminar servicio de vigilancia");
        menuServiciosVigilanciaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosVigilanciaEliminarActionPerformed(evt);
            }
        });
        menuServiciosVigilancia.add(menuServiciosVigilanciaEliminar);

        menuServicios.add(menuServiciosVigilancia);

        menuServiciosProvedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/transmit_go.png"))); // NOI18N
        menuServiciosProvedores.setText("Proveedores");

        menuServiciosProvedoresAgregar.setText("Agregar proveedor");
        menuServiciosProvedoresAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosProvedoresAgregarActionPerformed(evt);
            }
        });
        menuServiciosProvedores.add(menuServiciosProvedoresAgregar);

        menuServiciosProvedoresConsultar.setText("Consultar o Editar proveedor");
        menuServiciosProvedoresConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosProvedoresConsultarActionPerformed(evt);
            }
        });
        menuServiciosProvedores.add(menuServiciosProvedoresConsultar);

        menuServiciosProvedoresEliminar.setText("Eliminar proveedor");
        menuServiciosProvedoresEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosProvedoresEliminarActionPerformed(evt);
            }
        });
        menuServiciosProvedores.add(menuServiciosProvedoresEliminar);
        menuServiciosProvedores.add(menuServiciosProvedorSeparador);

        menuServiciosProvedorAgregarProductos.setText("Agregar Productos");
        menuServiciosProvedores.add(menuServiciosProvedorAgregarProductos);

        menusSeriviciosProvedoreEditarProductos.setText("Editar Productos");
        menuServiciosProvedores.add(menusSeriviciosProvedoreEditarProductos);

        menuServiciosProvedorEliminarProductos.setText("Eliminar Productos");
        menuServiciosProvedores.add(menuServiciosProvedorEliminarProductos);

        menuServicios.add(menuServiciosProvedores);
        menuServicios.add(menuServiciosSeparador);

        menuServiciosEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/chart_bar_edit.png"))); // NOI18N
        menuServiciosEstadisticas.setText("Estadisticas");
        menuServiciosEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosEstadisticasActionPerformed(evt);
            }
        });
        menuServicios.add(menuServiciosEstadisticas);

        menuBar.add(menuServicios);

        menuUbicaciones.setText("Ubicaciones");

        menuUbicacionesHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/calendar_view_week.png"))); // NOI18N
        menuUbicacionesHorarios.setText("Horarios");

        menuUbicacionesHorarioAgregar.setText("Agregar nuevo horario");
        menuUbicacionesHorarioAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUbicacionesHorarioAgregarActionPerformed(evt);
            }
        });
        menuUbicacionesHorarios.add(menuUbicacionesHorarioAgregar);

        menuUbicacionesHorariosEliminar.setText("Ver todos los horarios");
        menuUbicacionesHorariosEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUbicacionesHorariosEliminarActionPerformed(evt);
            }
        });
        menuUbicacionesHorarios.add(menuUbicacionesHorariosEliminar);

        menuUbicaciones.add(menuUbicacionesHorarios);

        menuUbicacionesLugares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/world.png"))); // NOI18N
        menuUbicacionesLugares.setText("Lugares");

        menuUbicacionesLugarNuevo.setText("Nuevo lugar");
        menuUbicacionesLugarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUbicacionesLugarNuevoActionPerformed(evt);
            }
        });
        menuUbicacionesLugares.add(menuUbicacionesLugarNuevo);

        menuUbicacionesLugarConsulta.setText("Consulta de lugares");
        menuUbicacionesLugarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUbicacionesLugarConsultaActionPerformed(evt);
            }
        });
        menuUbicacionesLugares.add(menuUbicacionesLugarConsulta);

        menuUbicaciones.add(menuUbicacionesLugares);

        menuBar.add(menuUbicaciones);

        menuHistorial.setText("Personal");

        menuHistorialTiendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/edit_group.png"))); // NOI18N
        menuHistorialTiendas.setText("Personal Tiendas");
        menuHistorial.add(menuHistorialTiendas);

        menuHistorialCentros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/edit_group.png"))); // NOI18N
        menuHistorialCentros.setText("Personal Centros");
        menuHistorialCentros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistorialCentrosActionPerformed(evt);
            }
        });
        menuHistorial.add(menuHistorialCentros);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wd/gui/Iconos/chart_bar_edit.png"))); // NOI18N
        jMenuItem3.setText("Estadísticas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuHistorial.add(jMenuItem3);

        menuBar.add(menuHistorial);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUbicacionesHorarioAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUbicacionesHorarioAgregarActionPerformed
            controlGeneralGui = new ControlGui ();
            controlGeneralGui.iniciarVentanaNuevoHorario(true);
    }//GEN-LAST:event_menuUbicacionesHorarioAgregarActionPerformed

    private void menuCentroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroRegistroActionPerformed
       Vector<Lugar> result = null;
       this.controlGuiLugar = new ControlGuiLugar();
       result = this.controlGuiLugar.traerTodosLosLugares(1);
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaAgregarCentro(true,result);
    }//GEN-LAST:event_menuCentroRegistroActionPerformed

    private void menuUbicacionesHorariosEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUbicacionesHorariosEliminarActionPerformed
           Vector<Horario> result = null;
           this.controlGuiHorario = new ControlGuiHorario();
           result = this.controlGuiHorario.traerTodosLosHorarios();
           this.controlGeneralGui = new ControlGui();
           this.controlGeneralGui.iniciarVentanaConsultarHorario(true, result);
    }//GEN-LAST:event_menuUbicacionesHorariosEliminarActionPerformed

    private void menuProductosDepartamentosAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosDepartamentosAgregarActionPerformed
        controlGeneralGui = new ControlGui ();
        controlGeneralGui.iniciarVentanaAgregarDepartamento(true);
    }//GEN-LAST:event_menuProductosDepartamentosAgregarActionPerformed

    private void menuProductosDepartamentosConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosDepartamentosConsultarActionPerformed

        Vector<Departamento> result = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        result = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaConsultarDepartamentos(true, result);
    }//GEN-LAST:event_menuProductosDepartamentosConsultarActionPerformed

    private void menuProductosDepartamentosEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosDepartamentosEliminarActionPerformed
        Vector<Departamento> result = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        result = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaEliminarDepartamento(true, result);
    }//GEN-LAST:event_menuProductosDepartamentosEliminarActionPerformed

    private void menuProductosDepartamentosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosDepartamentosEditarActionPerformed
        Vector<Departamento> result = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        result = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaModificarDepartamento(true, result);
    }//GEN-LAST:event_menuProductosDepartamentosEditarActionPerformed

    private void menuUbicacionesLugarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUbicacionesLugarConsultaActionPerformed
        Vector<Lugar> resultadoEdo = null;
        Vector<Lugar> resultadoCiudad = null;
        this.controlGuiLugar = new ControlGuiLugar();
        resultadoEdo = this.controlGuiLugar.traerTodosLosLugares(1);
        resultadoCiudad = this.controlGuiLugar.traerTodosLosLugares(2);
        controlGeneralGui = new  ControlGui();
        controlGeneralGui.iniciarVentanaConsultaLugares(true, resultadoEdo,
                                                        resultadoCiudad);
    }//GEN-LAST:event_menuUbicacionesLugarConsultaActionPerformed

    private void menuProductosClaseAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosClaseAgregarActionPerformed
        Vector<Departamento> result = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        result = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaAgregarClase(true, result);
    }//GEN-LAST:event_menuProductosClaseAgregarActionPerformed

    private void menuProductosClaseConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosClaseConsultarActionPerformed
        Vector<Departamento> dptos = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        dptos = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaConsultarClase(true, dptos);
    }//GEN-LAST:event_menuProductosClaseConsultarActionPerformed

    private void menuProductosClaseEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosClaseEliminarActionPerformed
        Vector<Departamento> dptos = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        dptos = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaEliminarClase(true, dptos);
    }//GEN-LAST:event_menuProductosClaseEliminarActionPerformed

    private void menuProductosClaseEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosClaseEditarActionPerformed
        Vector<Departamento> dptos = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        dptos = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaModificarClase(true, dptos);
    }//GEN-LAST:event_menuProductosClaseEditarActionPerformed

    private void menuProductosSubAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosSubAgregarActionPerformed
        Vector<Departamento> dptos = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        dptos = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaAgregarSubClase(true, dptos);
    }//GEN-LAST:event_menuProductosSubAgregarActionPerformed

    private void menuProductosSubEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosSubEliminarActionPerformed
        Vector<Departamento> dptos = null;
        this.controlGuiDepartamento = new ControlGuiDepartamento();
        dptos = this.controlGuiDepartamento.traerTodosLosDepartamentos();
        controlGeneralGui = new ControlGui();
        controlGeneralGui.iniciarVentanaEliminarSubClase(true, dptos);
    }//GEN-LAST:event_menuProductosSubEliminarActionPerformed

    private void menuCentroConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroConsultarActionPerformed
       Vector<Lugar> result = null;
       this.controlGuiLugar = new ControlGuiLugar();
       result = this.controlGuiLugar.traerTodosLosLugares(1);
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaConsultarCentro(true,result);
    }//GEN-LAST:event_menuCentroConsultarActionPerformed

    private void menuUbicacionesLugarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUbicacionesLugarNuevoActionPerformed
        Collection<Lugar> result = null;
        this.controlGuiLugar = new ControlGuiLugar();
        result = this.controlGuiLugar.traerTodosLosLugares(1);
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaAgregarLugar(true, result);
    }//GEN-LAST:event_menuUbicacionesLugarNuevoActionPerformed

    private void menuServiciosProvedoresAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosProvedoresAgregarActionPerformed
        Collection<Lugar> result = null;
        this.controlGuiLugar = new ControlGuiLugar();
        result = this.controlGuiLugar.traerTodosLosLugares(2);
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaAgregarProveedor(true, result);
    }//GEN-LAST:event_menuServiciosProvedoresAgregarActionPerformed

    private void menuServiciosProvedoresConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosProvedoresConsultarActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaEdiConProveedor1(true);
    }//GEN-LAST:event_menuServiciosProvedoresConsultarActionPerformed

    private void menuCentroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroEliminarActionPerformed
        Vector<Lugar> result = null;
        this.controlGuiLugar = new ControlGuiLugar();
        result = this.controlGuiLugar.traerTodosLosLugares(1);
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaEliminarCentro(true, result);
    }//GEN-LAST:event_menuCentroEliminarActionPerformed

    private void menuServiciosProvedoresEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosProvedoresEliminarActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarCerrarVentanaEliminarProve(true);
    }//GEN-LAST:event_menuServiciosProvedoresEliminarActionPerformed

    private void menuCentroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroEditarActionPerformed
        Vector<Lugar> result = null;
        this.controlGuiLugar = new ControlGuiLugar();
        result = this.controlGuiLugar.traerTodosLosLugares(1);
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaModificarCentro(true, result);
    }//GEN-LAST:event_menuCentroEditarActionPerformed

    private void menuAgregarEmpleadoTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarEmpleadoTiendaActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarCerrarVentanaAgEmpTienda(true);
    }//GEN-LAST:event_menuAgregarEmpleadoTiendaActionPerformed

    private void MenuProductosAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductosAgregarActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaAgregarProducto(true);
    }//GEN-LAST:event_MenuProductosAgregarActionPerformed

    private void menuServiciosVigilanciaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosVigilanciaAgregarActionPerformed
        Vector<Lugar> result = null;
       this.controlGuiLugar = new ControlGuiLugar();
       result = this.controlGuiLugar.traerTodosLosLugares(1);
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaAgregarEmpresaVigilancia(true,result);
    }//GEN-LAST:event_menuServiciosVigilanciaAgregarActionPerformed

    private void menuEditarEmpleadoTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarEmpleadoTiendaActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarCerrarVentanaConsultaEmpTienda(true);
    }//GEN-LAST:event_menuEditarEmpleadoTiendaActionPerformed

    private void menuServiciosVigilanciaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosVigilanciaConsultarActionPerformed
       Vector<Lugar> result = null;
       this.controlGuiLugar = new ControlGuiLugar();
       result = this.controlGuiLugar.traerTodosLosLugares(1);
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaConsultarEmpresaVigilancia(true,result);
    }//GEN-LAST:event_menuServiciosVigilanciaConsultarActionPerformed

    private void menuEliminarEmpleadoTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarEmpleadoTiendaActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarCerrarVentanaEliminarEmp(true);
    }//GEN-LAST:event_menuEliminarEmpleadoTiendaActionPerformed

    private void menuRegistrarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarTiendaActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaAgregarTienda(true);
    }//GEN-LAST:event_menuRegistrarTiendaActionPerformed

    private void menuServiciosVigilanciaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosVigilanciaEliminarActionPerformed
       Vector<Lugar> result = null;
       this.controlGuiLugar = new ControlGuiLugar();
       result = this.controlGuiLugar.traerTodosLosLugares(1);
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaEliminarEmpresaVigilancia(true,result);
    }//GEN-LAST:event_menuServiciosVigilanciaEliminarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVenAgregarVigilanciaCentro(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuServiciosVigilanciaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosVigilanciaEditarActionPerformed
        Vector<Lugar> result = null;
       this.controlGuiLugar = new ControlGuiLugar();
       result = this.controlGuiLugar.traerTodosLosLugares(1);
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaModificarEmpresaVigilancia(true,result);
    }//GEN-LAST:event_menuServiciosVigilanciaEditarActionPerformed

    private void menuEditarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarTiendaActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaModificarTienda(true);
    }//GEN-LAST:event_menuEditarTiendaActionPerformed

    private void menuConsultarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarTiendaActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaConsultarTienda(true);
    }//GEN-LAST:event_menuConsultarTiendaActionPerformed

    private void menuEliminarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarTiendaActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaEliminarTienda(true);
    }//GEN-LAST:event_menuEliminarTiendaActionPerformed

    private void menuProductosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosEditarActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaEditarProducto(true);
    }//GEN-LAST:event_menuProductosEditarActionPerformed

    private void menuProductosConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosConsultarActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaConsultaProducto(true);
    }//GEN-LAST:event_menuProductosConsultarActionPerformed

    private void menuEstadisticasTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadisticasTiendaActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniVenestadisticasTienda(true);
    }//GEN-LAST:event_menuEstadisticasTiendaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniVenestadisticasPersonal(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuHistorialCentrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistorialCentrosActionPerformed
       Vector<CentroDistribucion> result = null;
       this.controlGuiCentro = new ControlGuiCentroDistribucion();
       result = this.controlGuiCentro.traerTodosLosCentros();
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaPersonalCentro(true,result);
    }//GEN-LAST:event_menuHistorialCentrosActionPerformed

    private void menuCentroInventarioConsultarProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroInventarioConsultarProvedoresActionPerformed
        Vector<CentroDistribucion> result = null;
       this.controlGuiCentro = new ControlGuiCentroDistribucion();
       result = this.controlGuiCentro.traerTodosLosCentros();
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaProveedoresCentro(true,result);
    }//GEN-LAST:event_menuCentroInventarioConsultarProvedoresActionPerformed

    private void menuConsultaInventarioTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaInventarioTiendaActionPerformed
       Vector<Tienda> result = null;
       this.controlGuiTienda = new ControlGuiTienda();
       result = this.controlGuiTienda.consultarTiendas();
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaConsultaInventarioTienda(true,result);
    }//GEN-LAST:event_menuConsultaInventarioTiendaActionPerformed

    private void menuCentroInventarioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroInventarioConsultarActionPerformed
       Vector<CentroDistribucion> result = null;
       this.controlGuiCentro = new ControlGuiCentroDistribucion();
       result = this.controlGuiCentro.traerTodosLosCentros();
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaConsultaInventarioCentro(true,result);
    }//GEN-LAST:event_menuCentroInventarioConsultarActionPerformed

    private void menuProductosEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosEliminarActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaEliminarProducto(true);
    }//GEN-LAST:event_menuProductosEliminarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.ivenOc(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuTransferirEmpleadoTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransferirEmpleadoTiendaActionPerformed
        Vector<Tienda> result = null;
       this.controlGuiTienda = new ControlGuiTienda();
       result = this.controlGuiTienda.consultarTiendas();
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaTransferenciaEmpTiendas(true,result);
    }//GEN-LAST:event_menuTransferirEmpleadoTiendaActionPerformed

    private void menuProductosConsultarPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosConsultarPreciosActionPerformed
       Vector<Producto> result = null;
       this.controlGuiProducto = new ControlGuiProducto();
       result = this.controlGuiProducto.traerTodosLosProductos();
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaConsultarPrecioProducto(true,result);
    }//GEN-LAST:event_menuProductosConsultarPreciosActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.ivenAoc(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuCentroNominaEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroNominaEditarEmpleadoActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarCerrarVentanaConsultaEmpleadoCentro(true);
    }//GEN-LAST:event_menuCentroNominaEditarEmpleadoActionPerformed

    private void menuCentroNominaEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroNominaEliminarEmpleadoActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaEliminarEmpleadoCentro(true);
    }//GEN-LAST:event_menuCentroNominaEliminarEmpleadoActionPerformed

    private void menuCentroNominaAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroNominaAgregarEmpleadoActionPerformed
        this.controlGeneralGui = new ControlGui();
        this.controlGeneralGui.iniciarVentanaRegistrarEmpleadoCentro(true);
    }//GEN-LAST:event_menuCentroNominaAgregarEmpleadoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuCentroAsignarProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroAsignarProvedoresActionPerformed
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.ivenAsignarProveCen(true);
    }//GEN-LAST:event_menuCentroAsignarProvedoresActionPerformed

    private void menuCentroCamionRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroCamionRegistroActionPerformed
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaAgregarCamion(true);
    }//GEN-LAST:event_menuCentroCamionRegistroActionPerformed

    private void menuCentroCamionEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroCamionEditarActionPerformed
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaEditarCamion(true);
    }//GEN-LAST:event_menuCentroCamionEditarActionPerformed

    private void menuCentroCamionConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroCamionConsultaActionPerformed
        this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaConsultarCamion(true);
    }//GEN-LAST:event_menuCentroCamionConsultaActionPerformed

    private void menuCentroCamionEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroCamionEliminarActionPerformed
         this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaEliminarCamion(true);
    }//GEN-LAST:event_menuCentroCamionEliminarActionPerformed

    private void menuServiciosEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosEstadisticasActionPerformed
       this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaEstadisticasServicios(true);
    }//GEN-LAST:event_menuServiciosEstadisticasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VentanaProcesarPedidoSeleccion ven = new VentanaProcesarPedidoSeleccion();
        ven.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuProductosEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosEstadisticasActionPerformed
        this.controlGeneralGui = new ControlGui();
       this.controlGeneralGui.iniciarVentanaEstadisticasProducto(true);
    }//GEN-LAST:event_menuProductosEstadisticasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuProductosAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem menuAgregarEmpleadoTienda;
    private javax.swing.JMenuItem menuArcecaDe;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCentroAsignarProvedores;
    private javax.swing.JMenuItem menuCentroCamionAgregarCamionSuelto;
    private javax.swing.JMenuItem menuCentroCamionConsulta;
    private javax.swing.JMenuItem menuCentroCamionEditar;
    private javax.swing.JMenuItem menuCentroCamionEliminar;
    private javax.swing.JMenuItem menuCentroCamionRegistro;
    private javax.swing.JMenu menuCentroCamiones;
    private javax.swing.JMenuItem menuCentroConsultar;
    private javax.swing.JMenuItem menuCentroEditar;
    private javax.swing.JMenuItem menuCentroEliminar;
    private javax.swing.JMenuItem menuCentroEstadisticas;
    private javax.swing.JMenuItem menuCentroInventarioConsultar;
    private javax.swing.JMenuItem menuCentroInventarioConsultarProvedores;
    private javax.swing.JMenu menuCentroInventarios;
    private javax.swing.JMenu menuCentroMantenimiento;
    private javax.swing.JMenu menuCentroNomina;
    private javax.swing.JMenuItem menuCentroNominaAgregarEmpleado;
    private javax.swing.JMenuItem menuCentroNominaEditarEmpleado;
    private javax.swing.JMenuItem menuCentroNominaEliminarEmpleado;
    private javax.swing.JSeparator menuCentroNominaSeparador;
    private javax.swing.JMenuItem menuCentroNominaTrasnferirEmpelado;
    private javax.swing.JMenuItem menuCentroRegistro;
    private javax.swing.JSeparator menuCentroSeparador;
    private javax.swing.JMenu menuCentroSolicitudes;
    private javax.swing.JMenuItem menuCentroSolicitudesPedidosTiendas;
    private javax.swing.JMenu menuCentros;
    private javax.swing.JMenuItem menuConsultaCentrosTienda;
    private javax.swing.JMenuItem menuConsultaInventarioTienda;
    private javax.swing.JMenuItem menuConsultarTienda;
    private javax.swing.JMenuItem menuEditarEmpleadoTienda;
    private javax.swing.JMenuItem menuEditarTienda;
    private javax.swing.JMenuItem menuEliminarEmpleadoTienda;
    private javax.swing.JMenuItem menuEliminarTienda;
    private javax.swing.JMenuItem menuEstadisticasTienda;
    private javax.swing.JMenu menuHistorial;
    private javax.swing.JMenuItem menuHistorialCentros;
    private javax.swing.JMenuItem menuHistorialTiendas;
    private javax.swing.JMenu menuInventarioTienda;
    private javax.swing.JMenu menuMantenimientoTienda;
    private javax.swing.JMenu menuNominaTienda;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenuItem menuProductosClaseAgregar;
    private javax.swing.JMenuItem menuProductosClaseConsultar;
    private javax.swing.JMenuItem menuProductosClaseEditar;
    private javax.swing.JMenuItem menuProductosClaseEliminar;
    private javax.swing.JMenu menuProductosClases;
    private javax.swing.JMenuItem menuProductosConsultar;
    private javax.swing.JMenuItem menuProductosConsultarPrecios;
    private javax.swing.JMenu menuProductosDepartamentos;
    private javax.swing.JMenuItem menuProductosDepartamentosAgregar;
    private javax.swing.JMenuItem menuProductosDepartamentosConsultar;
    private javax.swing.JMenuItem menuProductosDepartamentosEditar;
    private javax.swing.JMenuItem menuProductosDepartamentosEliminar;
    private javax.swing.JMenuItem menuProductosEditar;
    private javax.swing.JMenuItem menuProductosEliminar;
    private javax.swing.JMenuItem menuProductosEstadisticas;
    private javax.swing.JMenu menuProductosMantenimiento;
    private javax.swing.JSeparator menuProductosSeparador;
    private javax.swing.JMenuItem menuProductosSubAgregar;
    private javax.swing.JMenu menuProductosSubClases;
    private javax.swing.JMenuItem menuProductosSubConsultar;
    private javax.swing.JMenuItem menuProductosSubEliminar;
    private javax.swing.JMenuItem menuRegistrarTienda;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JSeparator menuSeparadorDosTienda;
    private javax.swing.JSeparator menuSeparadorTienda;
    private javax.swing.JMenu menuServicios;
    private javax.swing.JMenuItem menuServiciosEstadisticas;
    private javax.swing.JMenuItem menuServiciosProvedorAgregarProductos;
    private javax.swing.JMenuItem menuServiciosProvedorEliminarProductos;
    private javax.swing.JSeparator menuServiciosProvedorSeparador;
    private javax.swing.JMenu menuServiciosProvedores;
    private javax.swing.JMenuItem menuServiciosProvedoresAgregar;
    private javax.swing.JMenuItem menuServiciosProvedoresConsultar;
    private javax.swing.JMenuItem menuServiciosProvedoresEliminar;
    private javax.swing.JSeparator menuServiciosSeparador;
    private javax.swing.JMenu menuServiciosVigilancia;
    private javax.swing.JMenuItem menuServiciosVigilanciaAgregar;
    private javax.swing.JMenuItem menuServiciosVigilanciaConsultar;
    private javax.swing.JMenuItem menuServiciosVigilanciaEditar;
    private javax.swing.JMenuItem menuServiciosVigilanciaEliminar;
    private javax.swing.JMenu menuSolicitudesTienda;
    private javax.swing.JMenu menuTiendas;
    private javax.swing.JSeparator menuTiendasSeparador;
    private javax.swing.JMenuItem menuTransferenciasTienda;
    private javax.swing.JMenuItem menuTransferirEmpleadoTienda;
    private javax.swing.JMenu menuUbicaciones;
    private javax.swing.JMenuItem menuUbicacionesHorarioAgregar;
    private javax.swing.JMenu menuUbicacionesHorarios;
    private javax.swing.JMenuItem menuUbicacionesHorariosEliminar;
    private javax.swing.JMenuItem menuUbicacionesLugarConsulta;
    private javax.swing.JMenuItem menuUbicacionesLugarNuevo;
    private javax.swing.JMenu menuUbicacionesLugares;
    private javax.swing.JMenuItem menusSeriviciosProvedoreEditarProductos;
    // End of variables declaration//GEN-END:variables

}
